### ISSUE TITLE
Notifications are not showing on Windows 10

### ISSUE THREAD

**Issue by wira** [chinleung/sw-exporter-run-notifier#1]
from [here ](https://electronjs.org/docs/tutorial/notifications#windows)

you need to enable AUMID,
`app.setAppUserModelId('com.electron.sw-exporter');`

> com.electron.sw-exporter

is from the appId listed on sw-exporter package.json file

**Comment by chinleung** [comment]
@wira I think this has to be done in SWEX itself as I do not have access to the `app` variable via the plugin. I'll have a look at it but I got it working on my W10 without that. 🤔

**Comment by wira** [comment]
@chinleung maybe difference in the windows version? (mine is whatever the latest, can't check on work now). I tried before without that line and the notification did not show. You can require `app` together with `Notification`.

Although I agree that this better be done in SWEX.

**Comment by chinleung** [comment]
@wira Can you try the new SWEX to see if it's working now with the `setAppUserModelId`? Also, please make sure to enable notifications in your Windows 10 settings.

Let me know if you cannot compile SWEX, I can try to send you a new compiled version.

**Comment by wira** [comment]
I got it working now with latest SWEX, thanks @chinleung
